### ISSUE TITLE
Installation crashes on Node 12

### ISSUE THREAD

**Issue by funmaker** [Rantanen/node-celt#10]
node-celt crashes when compiled on Node 12. Reverting back to Node 11 fixes the issue.

```
$ npm i celt

> celt@0.1.12 install /home/funmaker/Desktop/kek/celt/node_modules/celt
> node-gyp rebuild

make: Entering directory '/home/funmaker/Desktop/kek/celt/node_modules/celt/build'
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/bands.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/celt.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/cwrs.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/entcode.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/entdec.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/entenc.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/header.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/kiss_fft.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/laplace.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/mdct.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/modes.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/pitch.o
../deps/celt-0.7.1/libcelt/pitch.c: In function ‘find_best_pitch’:
../deps/celt-0.7.1/libcelt/pitch.c:71:13: warning: variable ‘score’ set but not used [-Wunused-but-set-variable]
   71 |       float score;
      |             ^~~~~
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/quant_bands.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/rangedec.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/rangeenc.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/rate.o
  CC(target) Release/obj.target/libcelt/deps/celt-0.7.1/libcelt/vq.o
  AR(target) Release/obj.target/deps/celt.a
  COPY Release/celt.a
  CXX(target) Release/obj.target/node-celt/src/node-celt.o
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:202,
                 from ../src/node-celt.cc:8:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:18:51: warning: ‘v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
   18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
      |                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
   22 | X(Boolean)
      | ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2537:59: note: declared here
 2537 |                 V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
      |                                                           ^~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../../nan/nan_converters.h:67,
                 from ../../nan/nan.h:202,
                 from ../src/node-celt.cc:8:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:37:57: warning: ‘v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const’ is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
      |                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
   40 | X(bool, Boolean)
      | ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2575:51: note: declared here
 2575 |                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
      |                                                   ^~~~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/node-celt.cc:8:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
  103 |   return scope.Escape(v8::Function::New( isolate
      |                                          ^~~~~~~
      |                                          |
      |                                          v8::Isolate*
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:4139:22: note:   initializing argument 1 of ‘static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)’
 4139 |       Local<Context> context, FunctionCallback callback,
      |       ~~~~~~~~~~~~~~~^~~~~~~
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/node-celt.cc:8:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                     ^
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:5394:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
 5394 |   static Local<Value> New(Isolate* isolate, Local<String> value);
      |                       ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:5394:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189,
                 from ../../nan/nan.h:203,
                 from ../src/node-celt.cc:8:
../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                          ^
../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                            ^
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1034:53: error: no matching function for call to ‘v8::Value::ToString()’
 1034 |       v8::Local<v8::String> string = from->ToString();
      |                                                     ^
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2541:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
 2541 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
      |                                            ^~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2541:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2557:31: note: candidate: ‘v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const’
 2557 |                 Local<String> ToString(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2557:31: note:   candidate expects 1 argument, 0 provided
 2557 |                 Local<String> ToString(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
 1044 |         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
      |                                     ^~~~
      |                                     |
      |                                     char*
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2751:26: note:   initializing argument 1 of ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
 2751 |   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
      |                 ~~~~~~~~~^~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1818:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1818 |     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
      |                                                                ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:3372:22: note: declared here
 3372 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1824:42: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1824 |     New(persistentHandle)->Set(key, value);
      |                                          ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:3372:22: note: declared here
 3372 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
../../nan/nan.h:1830:44: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1830 |     New(persistentHandle)->Set(index, value);
      |                                            ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:3381:22: note: declared here
 3381 |                 bool Set(uint32_t index, Local<Value> value));
      |                      ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1836:61: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1836 |         New(persistentHandle)->Get(New(key).ToLocalChecked()));
      |                                                             ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:3425:51: note: declared here
 3425 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
../../nan/nan.h:1842:55: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1842 |     return scope.Escape(New(persistentHandle)->Get(key));
      |                                                       ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:3425:51: note: declared here
 3425 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
      |                                                   ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
../../nan/nan.h:1847:57: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 1847 |     return scope.Escape(New(persistentHandle)->Get(index));
      |                                                         ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:3429:51: note: declared here
 3429 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
      |                                                   ^~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/node-celt.cc:8:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2167:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2167 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /usr/include/c++/9.1.0/cassert:44,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/node_object_wrap.h:26,
                 from ../src/node-celt.cc:5:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   24 |     assert(persistent().IsNearDeath());
      |                         ^~~~~~~~~~~
In file included from ../../nan/nan.h:2657,
                 from ../src/node-celt.cc:8:
../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../nan/nan_object_wrap.h:67:34: warning: ‘void v8::PersistentBase<T>::MarkIndependent() [with T = v8::Object]’ is deprecated: Weak objects are always considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
   67 |     persistent().MarkIndependent();
      |                                  ^
In file included from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8-internal.h:14,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:25,
                 from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:567:22: note: declared here
  567 |       V8_INLINE void MarkIndependent());
      |                      ^~~~~~~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from /usr/include/c++/9.1.0/cassert:44,
                 from /home/funmaker/.cache/node-gyp/12.9.0/include/node/node_object_wrap.h:26,
                 from ../src/node-celt.cc:5:
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  124 |     assert(wrap->handle_.IsNearDeath());
      |                          ^~~~~~~~~~~
../src/node-celt.cc: At global scope:
../src/node-celt.cc:133:20: error: ‘Handle’ has not been declared
  133 |   static void Init(Handle<Object> exports) {
      |                    ^~~~~~
../src/node-celt.cc:133:26: error: expected ‘,’ or ‘...’ before ‘<’ token
  133 |   static void Init(Handle<Object> exports) {
      |                          ^
In file included from ../src/node-celt.cc:7:
../src/node-celt.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE CeltEncoder::Encode(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/common.h:44:54: error: no matching function for call to ‘v8::Value::Int32Value()’
   44 |  CHECK_ARG( I, IsNumber(), VAR = info[I]->Int32Value(), VAR = DEFAULT )
      |                                                      ^
../src/common.h:29:70: note: in definition of macro ‘CHECK_ARG’
   29 |  if ( info.Length() <= (I) || !info[I]->CHECK ) { DO_FALSE; } else { DO_TRUE; }
      |                                                                      ^~~~~~~
../src/node-celt.cc:62:4: note: in expansion of macro ‘OPT_INT_ARG’
   62 |    OPT_INT_ARG( 1, compressedSize, 43 );
      |    ^~~~~~~~~~~
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2582 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-celt.cc:7:
../src/node-celt.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE CeltEncoder::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/common.h:44:54: error: no matching function for call to ‘v8::Value::Int32Value()’
   44 |  CHECK_ARG( I, IsNumber(), VAR = info[I]->Int32Value(), VAR = DEFAULT )
      |                                                      ^
../src/common.h:29:70: note: in definition of macro ‘CHECK_ARG’
   29 |  if ( info.Length() <= (I) || !info[I]->CHECK ) { DO_FALSE; } else { DO_TRUE; }
      |                                                                      ^~~~~~~
../src/node-celt.cc:114:4: note: in expansion of macro ‘OPT_INT_ARG’
  114 |    OPT_INT_ARG(0, rate, 42000);
      |    ^~~~~~~~~~~
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2582 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-celt.cc:7:
../src/common.h:44:54: error: no matching function for call to ‘v8::Value::Int32Value()’
   44 |  CHECK_ARG( I, IsNumber(), VAR = info[I]->Int32Value(), VAR = DEFAULT )
      |                                                      ^
../src/common.h:29:70: note: in definition of macro ‘CHECK_ARG’
   29 |  if ( info.Length() <= (I) || !info[I]->CHECK ) { DO_FALSE; } else { DO_TRUE; }
      |                                                                      ^~~~~~~
../src/node-celt.cc:115:4: note: in expansion of macro ‘OPT_INT_ARG’
  115 |    OPT_INT_ARG(1, size, rate/100);
      |    ^~~~~~~~~~~
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2582 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-celt.cc:7:
../src/node-celt.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE CeltEncoder::SetBitrate(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/common.h:40:32: error: no matching function for call to ‘v8::Value::Int32Value()’
   40 |  int VAR = info[I]->Int32Value()
      |                                ^
../src/node-celt.cc:125:4: note: in expansion of macro ‘REQ_INT_ARG’
  125 |    REQ_INT_ARG( 0, bitrate );
      |    ^~~~~~~~~~~
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
 2582 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
      |                                        ^~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:2582:40: note:   candidate expects 1 argument, 0 provided
../src/node-celt.cc: In static member function ‘static void CeltEncoder::Init(int)’:
../src/node-celt.cc:144:4: error: ‘exports’ was not declared in this scope
  144 |    exports->Set(Nan::New<String>("CeltEncoder").ToLocalChecked(), tpl->GetFunction());
      |    ^~~~~~~
../src/node-celt.cc:144:84: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
  144 | ew<String>("CeltEncoder").ToLocalChecked(), tpl->GetFunction());
      |                                                              ^

In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:5961:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 5961 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:5961:46: note:   candidate expects 1 argument, 0 provided
../src/node-celt.cc: At global scope:
../src/node-celt.cc:149:15: error: variable or field ‘NodeInit’ declared void
  149 | void NodeInit(Handle<Object> exports) {
      |               ^~~~~~
../src/node-celt.cc:149:15: error: ‘Handle’ was not declared in this scope
../src/node-celt.cc:149:28: error: expected primary-expression before ‘>’ token
  149 | void NodeInit(Handle<Object> exports) {
      |                            ^
../src/node-celt.cc:149:30: error: ‘exports’ was not declared in this scope
  149 | void NodeInit(Handle<Object> exports) {
      |                              ^~~~~~~
In file included from ../src/node-celt.cc:3:
../src/node-celt.cc:153:24: error: ‘NodeInit’ was not declared in this scope
  153 | NODE_MODULE(node_celt, NodeInit)
      |                        ^~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
  556 |       (node::addon_register_func) (regfunc),                          \
      |                                    ^~~~~~~
../src/node-celt.cc:153:1: note: in expansion of macro ‘NODE_MODULE’
  153 | NODE_MODULE(node_celt, NodeInit)
      | ^~~~~~~~~~~
In file included from ../src/node-celt.cc:2:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/funmaker/.cache/node-gyp/12.9.0/include/node/node_object_wrap.h:84:78:   required from here
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9893 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:66:61:   required from here
/home/funmaker/.cache/node-gyp/12.9.0/include/node/v8.h:9893:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [node-celt.target.mk:154: Release/obj.target/node-celt/src/node-celt.o] Error 1
make: Leaving directory '/home/funmaker/Desktop/kek/celt/node_modules/celt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.9-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/funmaker/Desktop/kek/celt/node_modules/celt
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok 
npm WARN kek@1.0.0 No description
npm WARN kek@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! celt@0.1.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the celt@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/funmaker/.npm/_logs/2019-08-26T21_12_05_555Z-debug.log
```

**Comment by acbetter** [comment]
Same Issue, here's debug log.
[2019-10-29T04_17_16_951Z-debug.log](https://github.com/Rantanen/node-celt/files/3781726/2019-10-29T04_17_16_951Z-debug.log)

**Comment by Rantanen** [comment]
Fixed now, Node 12 compatible version pushed as 0.1.14.
